services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul                                      # 시간대 설정         
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    mem_limit: 400m
    # MySQL 최적화 옵션 (t3.micro 메모리절약)
    # 성능 스키마 비활성화
    # 버퍼 풀 크기 조정
    # 최대 연결 수 조정 (151 -> 50)
    command: >
      --performance-schema=OFF
      --innodb-buffer-pool-size=128M
      --max-connections=50
    # restart: unless-stopped

  backend:
    image: star1431/guest-book-app-backend:latest         # 빌드x 이미지로 교체
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    # restart: unless-stopped                                       # 컨테이너 재시작 설정
    mem_limit: 350m
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_URL}                   # 프론트 주소 CORS
      TZ: Asia/Seoul                                      # 시간대 설정         
      JAVA_OPTS: "-Xmx280m -Xms180m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
      # JVM 최적화 (힙 300m, G1GC 사용, GC 일시정지 시간 제한)

  frontend:
    image: star1431/guest-book-app-frontend:latest        # 빌드x 이미지로 교체
    ports:
      - "3000:3000"
    depends_on:
      - backend
    mem_limit: 100m
    # restart: unless-stopped

volumes:
  mysql_data: