name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths: # push 된 파일이 이 경로에 있을 때만 실행
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/deploy.yml'  # 워크플로우 자체 수정 시에도 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps: # 각 작업 단계 정의
      - name: Check out code
        uses: actions/checkout@v4 # 코드 체크아웃 액션 사용

      - name: Login to Docker Hub 
        uses: docker/login-action@v3 # 도커 허브 로그인 액션 사용
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/guest-book-app-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/guest-book-app-backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/guest-book-app-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/guest-book-app-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0 # EC2 접속 액션 사용
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~
            docker-compose pull
            docker-compose up -d
            docker-compose ps